# -*- coding: utf-8 -*-
"""movie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7yGV_ooNiaIUkHSLW-eS7rlrgSWO9XC
"""

import pandas as pd
import numpy as np

movies=pd.read_csv('/content/tmdb_5000_movies.csv')

movies.head()

movies.columns

movies.info()

movies['tags']=movies['genres']+movies['overview']

movies.head()

new_df=movies[['id','title','genres','overview','tags']]

new_df=new_df.drop(columns=['genres','overview'])

new_df.head()

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=5000,stop_words='english')

cv

vec = cv.fit_transform(new_df['tags'].values.astype('U')).toarray()

vec

vec.shape

from sklearn.metrics.pairwise import cosine_similarity

sim=cosine_similarity(vec)

sim

new_df[new_df['title']=='The Dark Knight Rises']

dist=sorted(list(enumerate(sim[0])),reverse=True,key=lambda vec:vec[1])

dist

for i in dist[0:5]:
  print(new_df.iloc[i[0]].title)

def recommend(movies):
  """

  Args:
    movies:
  """
  index=new_df[new_df['title']==movies].index[0]
  distance=sorted(list(enumerate(sim[index])),reverse=True,key=lambda vec:vec[1])
  for i in distance[0:5]:
    print(new_df.iloc[i[0]].title)

recommend("Avatar")

recommend("The Fifth Element")